### ISSUE TITLE
WSL cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by hexadec1** [ricklamers/gridstudio#1]
Installed on latest Windows Subsystem Linux (Ubuntu kernel).  Unable to run run.sh, failed with error

```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

Steps to reproduce:
1. start WSL
2. apt-get install docker.io
3. git clone repo and cd into gridstudio-master
4. run ./run.sh

Fixes attempted:
1. sudo (naturally)
2. apt-get update
3. checked docker run --help to ensure docker was installed and running

**Comment by rcfox** [comment]
I don't know anything about WSL itself, but assuming that it's pulling from the Ubuntu (based on the apit-get command) repo it seems like you might be using an old version of Docker.

The official Docker install instructions recommend first uninstalling the docker.io Ubuntu package.

https://docs.docker.com/install/linux/docker-ce/ubuntu/

What version of docker do you have? (`docker --version`) You probably need to use version 18+.

**Comment by janikgar** [comment]
Are you running the Windows Insider build with WSL 2 + the Docker technical preview? If you are, you may want to check with Windows & Docker for updates.

Previous to that, Docker doesn't run natively inside WSL, so you'll need to install Docker Desktop for Windows and add an alias in your `.bashrc` to run a Windows install of Docker:
```
alias docker="docker.exe"
```
https://blogs.windows.com/windowsexperience/2019/06/12/announcing-windows-10-insider-preview-build-18917/
https://engineering.docker.com/2019/06/docker-hearts-wsl-2/

**Comment by hexadec1** [comment]
Docker version is 18.09.7, build 2d0083d.

**Comment by hexadec1** [comment]
Docker version is 18.09.7, build 2d0083d, running in WSL 1 currently. Attempted fix from @janikgar and that seems to be the correct answer. Corp machine blocked from downloading anything past 17.03 for Docker Windows version. Will try my home machine and report back.

If you are running into this as well:
-Uninstall docker.io from WSL
-Install Docker for Windows (version 18+)
-Edit (nano .bashrc with alias docker="docker.exe")
-Restart WSL shell
-Run run.sh
