### ISSUE TITLE
Doesn't install/run

### ISSUE THREAD

**Issue by BMaxV** [ricklamers/gridstudio#10]
Install says:

> 
> 2. Run the bash script (on Windows use e.g. Git Bash) with this command:
> 
> cd gridstudio && ./run.sh
> 

fish shell says:

> 
> /run.sh 
> Failed to execute process './run.sh'. Reason:
> exec: Exec format error
> The file './run.sh' is marked as an executable but could not be run by the operating system.
> 

bash says:

> 
> ./run.sh 
> ./run.sh: line 12: docker: command not found
> 

I'm on ubuntu19.04

**Comment by jacobgoldfarb** [comment]
Try adding a shebang like `#!/usr/bin/env bash` at the top.

**Comment by e-dt** [comment]
Install docker to fix

    ./run.sh
    ./run.sh: line 12: docker: command not found

**Comment by ricklamers** [comment]
Added shebang to .sh files, if that doesn't fix it please re-open.

**Comment by velascog** [comment]
installed in raspbian (linux) and when I run says:
standard_init_linux.go:211: exec user process caused "exec format error"
please help!
