### ISSUE TITLE
chinese looks like not support

### ISSUE THREAD

**Issue by yufengshizhe** [ricklamers/gridstudio#105]

**Comment by liuxilu** [comment]
sentence looks like not correct

**Comment by mding5692** [comment]
Can probably support internationalization with translations

**Comment by chrisspradling1980** [comment]
Hallelujah

**Comment by ricklamers** [comment]
I think Chinese characters are currently not supported. I haven't had a chance to expand the character set or do testing. Pull requests that fix this are welcome.
