### ISSUE TITLE
docker cmd not found

### ISSUE THREAD

**Issue by sleepmam** [ricklamers/gridstudio#108]
this might be some very basic issue, and I couldn't solve it bc I'm noob.

I ran the line of ->
git clone https://github.com/ricklamers/gridstudio

and when trying to run ->
cd gridstudio && ./run.sh

I got these two lines of error
 ->
./run.sh: line 17: docker: command not found
./run.sh: line 18: docker: command not found

*full picture attached*, OS X 10.15.1 (19B88)
<img width="516" alt="Screen Shot 2019-12-10 at 10 57 49" src="https://user-images.githubusercontent.com/26354538/70545878-494d1e80-1b3c-11ea-8fc6-5306c6d19368.png">

**Comment by sleepmam** [comment]
might also be related to issue of ->
127.0.0.1 refused to connect

**Comment by Dovermore** [comment]
Did you install docker? And does your PATH include the docker executable?
https://www.docker.com/

**Comment by Dovermore** [comment]
Also you have to run the docker first (if you used the desktop version same as me) before you run the script. Or it will prompt you something like docker not initialised.

**Comment by ricklamers** [comment]
Please try installing Docker first as per https://github.com/ricklamers/gridstudio/wiki/Installation
