### ISSUE TITLE
a text can't display in the cell.

### ISSUE THREAD

**Issue by neulf** [ricklamers/gridstudio#109]

**Comment by neulf** [comment]
![image](https://user-images.githubusercontent.com/1632729/71649689-b030b280-2d4b-11ea-86f3-a727cb6445e2.png)

**Comment by ricklamers** [comment]
It looks like you modified the ports on which it's running. Since custom ports aren't handled very nicely due to hardcoded ports over the codebase that could be the cause. Use 8080 and 4430 as per the defaults and try if the issue still persists.
