### ISSUE TITLE
Unable to find image 'ricklamers/gridstudio:release' locally

### ISSUE THREAD

**Issue by leisux** [ricklamers/gridstudio#110]
Hi, I use my Mac to try this app and I download docker first, then clone gridstudio, enter the directory in the terminal then ./run.sh. But it failed and shown "Unable to find image 'ricklamers/gridstudio:release' locally". I don't know why? Is there something wrong?

**Comment by ricklamers** [comment]
That shouldn't actually be a problem. It's expected behavior, and Docker should start downloading the Docker image from their Docker image repository. Please report back if it doesn't start working after you wait for a while.
