### ISSUE TITLE
Unable to find image 'ricklamers/gridstudio:release' locally

### ISSUE THREAD

**Issue by luobihui** [ricklamers/gridstudio#112]
Hi,I installed docker first and cloned gridstudio, then enter the directory in the terminal and ./run.sh. But it failed and shown
 "Unable to find image 'ricklamers/gridstudio:release' locally
release: Pulling from ricklamers/gridstudio
C:\Program Files\Docker\Docker\resources\bin\docker.exe: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/6c/6c1c903c739a4f0bd365e310bb42933e9e45cdf75c7c78cfd0f6cce1d2b955d6/data?verify=1583688215-Ul8%2FbBhfD2kahM9TMd94cTmcenE%3D: net/http: TLS handshake timeout.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'."
Is there something wrong?

**Comment by codebysandwich** [comment]
time out, pls try use mirror in docker.

**Comment by ricklamers** [comment]
Looks like it's your internet connection, if this issue persists please re-open and tell us a bit about what you tried. You could try re-installing Docker and trying again.

More details of similar issues can be found here: https://serverfault.com/a/913384.
