### ISSUE TITLE
Buggy scrolling when doing selection!

### ISSUE THREAD

**Issue by CyanideBoy** [ricklamers/gridstudio#117]
I am using ubuntu16 and firefox. The scrolling seems to be broken when in selection mode. I expected it to auto-scroll when I did Shift+Down Arrow but it gets stuck at the last row in display. The selection, however, does continue to go on below cells even after the display is stuck at the last cell of the visible grid. Moreover, using the cursor to scroll using the scrollbars is also pretty buggy. It scrolls randomly horizontally even though I am trying to use verticle scrollbars!

**Comment by ricklamers** [comment]
@CyanideBoy I've mainly developed and tested against Google Chrome. Please use that or Chromium for the best experience. Unfortunately cross platform development and testing takes quite some time.
