### ISSUE TITLE
127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by KyleYounghans** [ricklamers/gridstudio#12]
I followed the installation steps and ran in to the same problem as Soarnsky.  I used the code he posted to replace the 'cd gridstudio && ./run.sh and then I was able to get past that error.  However, when I go to 127.0.0.1:8008 I get the follow error in Chrome: This site can’t be reached 127.0.0.1 refused to connect.  I've confirmed Hyper-V is on and Visualization is active in the BIOS.  Any ideas on how to fix this?

**Comment by thewldr** [comment]
Trying to get the windows version running here as well.  I also ran into and fixed the run.sh problem adding ";D" to paths, which fixed that error.  However (adding --debug to run.sh) I'm running into the following issue.
```
$ ./run.sh
bash: run-manager-proxy.sh: No such file or directory
time="2019-07-29T16:11:56+09:00" level=debug msg="[hijack] End of stdout"
```
While I can't connect to localhost through Chrome, the container itself seems to launch fine:
  - Correctly gives an error that it's already running if I try to start it twice
  - Correctly gives an error if I run shutdown.sh when it's not running

**Comment by commonslash** [comment]
I was able to resolve this by:
Sharing my local drives (volumes) with Docker Desktop for Windows, so that they are available to my Linux containers. 
[https://docs.docker.com/docker-for-windows/#shared-drives](url)

Then going to the properties of the shared drive on Windows and enable sharing. Properties > Sharing > Advanced Sharing. This also required a restart.

**Comment by MiConnell** [comment]
@commonslash's comment fixed this issue for me!

**Comment by KyleYounghans** [comment]
@commonslash I tried that at it still isn't working.  When you installed Docker, did you use "Windows Containers" or "Linux Containers"

**Comment by ricklamers** [comment]
@KyleYounghans make sure you select Linux Containers. Indeed on Windows you need to explicitly share the drive on which you clone the git repo.

**Comment by KyleYounghans** [comment]
@ricklamers Thanks.  I'll give that a try later today or tomorrow and see if I can get it to work!

**Comment by ricklamers** [comment]
Please re-open this if you can't make it work ; )

**Comment by JasonMcCoy** [comment]
I have followed @commonslash instruction and still having this issue.
I am running on "Linux Containers" as well.

**Comment by ricklamers** [comment]
Hi @JasonMcCoy, after running `run.sh` what do you see as output on your terminal? I see that in OP the port is wrong. It says `127.0.0.1:8008` but should be `127.0.0.1:8080`. Could you give some more details about what issue you're experiencing?

**Comment by JasonMcCoy** [comment]
After executing the run.sh, a blank cmd prompt quickly pops up for a fraction of a second and then closes.
I’m aware the port was incorrect, but am still experiencing issues.

**Comment by ricklamers** [comment]
@JasonMcCoy are you running run.sh from Git Bash's MINGW terminal environment? I.e. in this kind of terminal?

![image](https://user-images.githubusercontent.com/1309307/62417490-608d7400-b651-11e9-83af-9ad66e9905ed.png)

**Comment by JasonMcCoy** [comment]
No, I tried running it in cmd and also by double clicking run.sh in the gridstudio folder.

When using Git Bash, I got the error: ‘docker: invalid reference format’. You posted a solution to the issue and I will report later if that solves my issue.
