### ISSUE TITLE
Can't display the interface on localhost

### ISSUE THREAD

**Issue by nefigarcia** [ricklamers/gridstudio#125]
Containers are running buy can't see the interface on the browsers. Using dockertoolbox on windows 7.
![run](https://user-images.githubusercontent.com/21102047/80380912-ccf67600-8865-11ea-9600-7275a0d01f65.JPG)
![listcontainers](https://user-images.githubusercontent.com/21102047/80380928-d2ec5700-8865-11ea-9f23-5efe2d539b48.PNG)
![local](https://user-images.githubusercontent.com/21102047/80380946-d7187480-8865-11ea-9a26-a2cd2e265e49.JPG)

**Comment by ricklamers** [comment]
Please check https://github.com/ricklamers/gridstudio/wiki/Installation

You need to run the provided shell script `run.sh` or copy code from it to make sure port `4430` and `8080` are being forwarded.
