### ISSUE TITLE
Can gridstudio import data form an exist excel?

### ISSUE THREAD

**Issue by Forgus** [ricklamers/gridstudio#126]
my question is,I already have an excel that contains a lot of data and it's unrealistic to fill in gridstudio again.So, can gridstudio import data form an exist excel?

**Comment by ricklamers** [comment]
Hi @Forgus you can easily use the excellent `pandas` package for this. Please check out https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
