### ISSUE TITLE
Issue cloning repository

### ISSUE THREAD

**Issue by rkbottoms** [ricklamers/gridstudio#15]
The files under the 'gridstudio/grid-app/static/xterm/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/' have filenames that are too long on Windows 10. The repository can't be cloned completely. 

Screenshot below: 
https://imgur.com/a/E4pSYGN

**Comment by ricklamers** [comment]
Removed the .cache from the repo. Good find. Open this issue if it still doesn't work for you.
