### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by robertosannazzaro** [ricklamers/gridstudio#16]
I am trying to run gridstudio but when I launch it with `./run.sh` i get the following error:

`docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.`

**Comment by robertosannazzaro** [comment]
The folder containing gridstudio was inside a folder which the name contained a capital letter. I solved this by changing the folder name.

**Comment by ricklamers** [comment]
Ah, good find. It's a limitation of Docker I guess.

**Comment by JasonMcCoy** [comment]
@robertosannazzaro or @ricklamers Do you mind clarifying how to resolve this issue? I am receiving the same error as well, but am not able to change the user's account name to all lowercase.

**Comment by ricklamers** [comment]
@JasonMcCoy Could you try putting the directory higher up on your drive? Are you on Windows? Perhaps `C:\gridstudio` directly or `C:\projects\gridstudio`?

**Comment by JasonMcCoy** [comment]
Oh ok, I know what op meant. I’ll try this in a couple hours and see if it resolves the issue.
I’m assuming it will.
Thank you.

**Comment by reflexiveprophecy** [comment]
I solved this problem by reading the following post:
https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase

Basically you gotta add quotation mark before '$' and before ':'.
For your convenience, replace your run.sh file to the following code:

`#!/usr/bin/env bash

if [[ "$OSTYPE" == "msys" ]]; then

	if [ ! "$(docker ps -a | grep gridstudio)" ]; then

		WIN_PWD=$PWD
		WIN_PWD=$(echo $WIN_PWD | sed -r 's/[/]+/\\/g')
		WIN_PWD=$(echo $WIN_PWD | sed -r 's/\\([a-z])\\+/\U\1:\\/g')

		docker run --name=gridstudio --rm=false -v "$WIN_PWD\\grid-app":/home/source -v "$WIN_PWD\\grid-app\\proxy\\userdata":/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
	else
		docker start gridstudio
	fi
else
	if [ ! "$(docker ps -a | grep gridstudio)" ]; then
		docker run --name=gridstudio --rm=false -v "$PWD/grid-app":/home/source -v "$PWD/grid-app/proxy/userdata":/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
	else
		docker start gridstudio
	fi
fi`
