### ISSUE TITLE
Issue running on Mac OS X Mojave

### ISSUE THREAD

**Issue by jbone** [ricklamers/gridstudio#17]
run.sh on my Mac yields the following error message (note, I'm running via sudo since /var/run apparently needs privilege to write the unix domain socket file.)

:; sudo ./run.sh 
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

--

Note that there is no such file:

:; ls -al /var/run/dock*
ls: /var/run/dock*: No such file or directory

--

I also killed a docker-related helper daemon prior to this;  there are no docker-related processes running when I run the runscript.

ps ax | grep -i docker
22686 s003  S+     0:00.00 grep -i docker

Thoughts?

jb

**Comment by mbafford** [comment]
I ran into this issue after installing docker from homebrew using:

```brew install docker```

I also needed to install docker from the cask:

```brew cask install docker```

Then run the macOS app `Docker.app` that was installed in `/Applications/`. The app asked for  my credentials so it could get elevated permissions and install system-level components.

Once that was done, docker commands, like `docker ps` worked, and running `gridstudio` worked. You shouldn't need to run `gridstudio` as root (`sudo ./run.sh`) - just `./run.sh` should work.

**Comment by ricklamers** [comment]
@mbafford says it exactly right. On Mac running the run.sh bash script shouldn't need sudo if Docker is properly installed. If following his steps on installing Docker doesn't work feel free to re-open this issue with additional info.

**Comment by sherrytp** [comment]
Hi ricklamers, 

Thank you for great service of gridstudio and answer. However, I had the issue running cd /run.sh . 
The error said "Cannot connect to the Docker daemon at unix:///var/run/docker.sock." 

I have docker installed and tried without sudo, but I believe the problem is with the connection? Could you please help? Thank you so much, and I wonder if you uploaded it to pypl so we can use pip install. 


Best, 

Sherry

**Comment by siegeout** [comment]
@sherrytp  I  found this problem just now and what you need to do is starting docker.app then run  "./run.sh ".

**Comment by ricklamers** [comment]
As @siegeout mentions - make sure Docker is running.

**Comment by jbone** [comment]
@all 

Followed @mbafford’s steps precisely, everything working for me now.  Thanks!

**Comment by ricklamers** [comment]
@jbone nice!

**Comment by sherrytp** [comment]
@siegeout Nice! Thanks, everyone!
