### ISSUE TITLE
Problem installing on Windows Server 2019

### ISSUE THREAD

**Issue by migdur** [ricklamers/gridstudio#18]
Hi,

I brought the install to the point of running run.sh on a Git bash console. Then I get:

C:\Program Files\Docker\docker.exe: image operating system "linux" cannot be used on this platform.

So the image is a linux image and cannot be run in Windows? How to sort this out?

Thanks for helping.

**Comment by gaoxiaoning** [comment]
yes,they are out cross-platform.

**Comment by ricklamers** [comment]
The Docker image is Linux based. So to get it to run on Windows you need Docker with Linux image runtime support at the moment.
