### ISSUE TITLE
Can't use python's module on my mac, like :requests , pymysql

### ISSUE THREAD

**Issue by t512192641** [ricklamers/gridstudio#22]
when i run the example on the gridstudio
the Error message always：No module named xx
so, how can i use the python's module on my mac?

https://github.com/ricklamers/gridstudio/blob/master/examples/scrape.py

**Comment by kollyQAQ** [comment]
the same question
hope to reply

**Comment by ricklamers** [comment]
The latest Docker image includes requests as a pre-installed Python module.

To fix these missing modules, you can run `pip3 install <module>` in the terminal of your Grid studio workspace.

**Comment by databill** [comment]
When this issue happens,  it was there if I use ``pip list`` and ``pip3 list``.
