### ISSUE TITLE
need log in?

### ISSUE THREAD

**Issue by chungehenzouhong** [ricklamers/gridstudio#24]
![image](https://user-images.githubusercontent.com/31273482/62260648-44b58280-b445-11e9-9439-14edf824bcb0.png)

**Comment by sunliwen** [comment]
I just use admin/admin as the hint suggested in Username field.

**Comment by chungehenzouhong** [comment]
got it thanks~

**Comment by ltcom2000** [comment]
I use admin/admin as the username, and what about the password?
I have tried blank password and the os system password, and i got 
incorrect-login

**Comment by chungehenzouhong** [comment]
> I use admin/admin as the username, and what about the password?
> I have tried blank password and the os system password, and i got
> incorrect-login

username:admin
pwd:admin

**Comment by ricklamers** [comment]
Default is indeed admin/admin. What do others think should happen here? Is the default unclear? Should login be removed entirely?

**Comment by AlJohri** [comment]
@ricklamers can you document it https://github.com/ricklamers/gridstudio/wiki/Installation
I ran `run.sh` and then got a login screen. wasn't sure what to do next

**Comment by ricklamers** [comment]
Added it, leaving it like this for now.
