### ISSUE TITLE
can‘t start

### ISSUE THREAD

**Issue by lrmc** [ricklamers/gridstudio#25]
bash: run-manager-proxy.sh: No such file or directory

how to fix it ,please

**Comment by amorZhu** [comment]
Did you install docker?

**Comment by ricklamers** [comment]
On what operating system are you using this? Could you provide some more details?

**Comment by thewldr** [comment]
Copying from a previous thread:

Trying to get the windows version running here as well. I also ran into and fixed the run.sh problem adding ";D" to paths, which fixed that error. However (adding --debug to run.sh) I'm running into the following issue.
```
$ ./run.sh
bash: run-manager-proxy.sh: No such file or directory
time="2019-07-29T16:11:56+09:00" level=debug msg="[hijack] End of stdout"
```
While I can't connect to localhost through Chrome, the container itself seems to launch fine:
- Docker correctly gives an error that it's already running if I try to start it twice
- Docker correctly gives an error if I run shutdown.sh when it's not running

Additionally, after dumping the container contents into a tar,
`$ docker export gridstudio > gridstudio.tar`
and inspecting it, I confirmed the file does exist in the right place, but isn't being found.

**Comment by ricklamers** [comment]
Could you try the latest Docker image from Docker hub?

Or are you using it?

**Comment by thewldr** [comment]
Setting everything up again by resetting Docker to factory defaults and pulling the latest off git seems to have (for me at least) solved the issue!  Thanks.

**Comment by ricklamers** [comment]
Nice!
