### ISSUE TITLE
miss file 'main.py'

### ISSUE THREAD

**Issue by bjbean** [ricklamers/gridstudio#26]
Error calling getFile for path: /home/userdata/workspace-a39ce24b-83ec-43c7-8219-522d3aaf4eef/userfolder/main.py
open /home/userdata/workspace-a39ce24b-83ec-43c7-8219-522d3aaf4eef/userfolder/main.py: no such file or directoryReceived WS in Client actions: {"arguments":["SWITCHSHEET","0"]}

**Comment by ricklamers** [comment]
By default Grid studio tries to open main.py (in /home/userdata/workspace-<uuid>/userfolder/) when you load the workspace. However, the error occurs when such a file has never been created (i.e. Go sees the file doesn't exists and logs the error). There's no harm in the error, the file just doesn't exist.

What would you recommend? Renaming the error to emphasize it's just trying to open a file that is not there?
