### ISSUE TITLE
Can not execute the example/estimate_normal.py

### ISSUE THREAD

**Issue by PeirongAn** [ricklamers/gridstudio#29]
step1.  start the grid studio and log in the website
step2.  copy the example/estimate_normal.py to the script window
step3. execute
However, the error msg showed like,
Traceback (most recent call last):
  File "python/init.py", line 282, in getAndExecuteInput
  File "<string>", line 1, in <module>
NameError: name 'time' is not defined

**Comment by PeirongAn** [comment]
https://hackernoon.com/introducing-grid-studio-a-spreadsheet-app-with-python-to-make-data-science-easier-tdup38f7

**Comment by lzyy** [comment]
I encounter the same problem, how did you fixed it?

**Comment by lzyy** [comment]
fixed it by select all the code...

**Comment by YanxiSir** [comment]
hi,bro，Have you fixed it?
