### ISSUE TITLE
after login it says 'attempt to write a readonly database'

### ISSUE THREAD

**Issue by cswxin** [ricklamers/gridstudio#30]
$ docker run --name=gridstudio --rm=false -v E:/gridstudio/grid-app:/home/source -v E:/gridstudio/grid-app/proxy/userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
Hashed PW: 19yxYLFN-1h1mow8cpqDqLlgsHo=
2019/08/02 03:21:26 attempt to write a readonly database
Login, found user matching hashed PW.
exit status 1

**Comment by ricklamers** [comment]
Are you sure drive E: is configured in Windows docker to be mounted (in the -v option)?

It looks like it might not be mounted with read/write which is causing the error when writing to the database sqlite file.

**Comment by cswxin** [comment]
![image](https://user-images.githubusercontent.com/9425725/62338940-e358e680-b50c-11e9-8af2-ca2763fa0819.png)

**Comment by ricklamers** [comment]
Could you check the file properties of "gridstudio\grid-app\proxy\db\manager.db"?

Does it happen to be Read-only?

Should be something like this: 

![image](https://user-images.githubusercontent.com/1309307/62399321-bc85c900-b57b-11e9-98b2-e751d88a7d77.png)

**Comment by cswxin** [comment]
no, it's not read-only

**Comment by ricklamers** [comment]
You're not touching the .db file with any other process (like a sqlite client or something?)

**Comment by ricklamers** [comment]
Have you tried cloning the directory again in a fresh directory? Do you get the same issue?

**Comment by tandelin1** [comment]
我的是在linux系统中使用的，数据库获取信息不到，我这边的处理方法是给docker中配置环境变量。保证linux系统中python能获取数据库的数据，下一步才考虑docker容器内获取数据库的数据，分解了问题，最后实现了

**Comment by ricklamers** [comment]
Only English in GitHub issues please - hope you understand.

**Comment by cswxin** [comment]
@tandelin1 老哥，怎么配环境变量的，我是在windows10下

**Comment by tandelin1** [comment]
https://blog.csdn.net/tandelin/article/details/98940498,我的是linux的环境变量配置，你容器如果是装在windows的话，你应该是在windows配置oracle的环境变量，下载安装oracle的客户端就可




------------------ 原始邮件 ------------------
发件人: "OceAn"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 中午11:15
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>; 
抄送: "此后行"<1525859926@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ricklamers/gridstudio] after login it says 'attempt to write areadonly database' (#30)




@tandelin1 老哥，怎么配环境变量的，我是在windows10下

**Comment by cswxin** [comment]
> @tandelin1

要装oracle?

**Comment by tandelin1** [comment]
我连接的是oracle，所以装的oracle客户端。看你那边是什么数据库，主要装的是一个如odbc.jar的驱动文件
------------------ 原始邮件 ------------------
发件人: "OceAn"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 中午11:29
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送: "此后行"<1525859926@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ricklamers/gridstudio] after login it says 'attempt to write areadonly database' (#30)



 
@tandelin1
  
要装oracle?

**Comment by ricklamers** [comment]
Inactivity close, feel free to re-open.
