### ISSUE TITLE
sed errors

### ISSUE THREAD

**Issue by AlJohri** [ricklamers/gridstudio#31]
Just tried running run.sh and ran into this error. Seems like the docker pull is continuing though.

![Screen Shot 2019-08-01 at 9 31 41 AM](https://user-images.githubusercontent.com/2790092/62297423-32d0e100-b43f-11e9-8464-c18ba074298d.png)

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by ricklamers** [comment]
Hmm, I guess MacOSX's sed doesn't support the option. Will try to look for a fix.

**Comment by AlJohri** [comment]
You can also use gsed installed via homebrew on macOS.

**Comment by ricklamers** [comment]
I've pushed an update. sed should now only be invoked on Windows Git Bash.
