### ISSUE TITLE
CSV import not working 

### ISSUE THREAD

**Issue by phoenix911** [ricklamers/gridstudio#32]
Not able to upload CSV. Am I missing something?

**Comment by ricklamers** [comment]
Hi phoenix911, what CSV are you trying to upload? Could you share the file or a sample row? I've just tried uploading a CSV on the latest build (Sample insurance portfolio - https://support.spatialkey.com/spatialkey-sample-csv-data/) and it seems to work on my end.

**Comment by tandelin1** [comment]
需要给csv文件赋予读取的权限，才能成功。

**Comment by ricklamers** [comment]
Only English in GitHub issues please - hope you understand.

**Comment by Twopence16** [comment]
Maybe gridstudio has a limit of rownumber,I fail to load a csv file(only one column) of about 1
million rows.But I can load samples from https://support.spatialkey.com/spatialkey-sample-csv-data/.

**Comment by ricklamers** [comment]
If a subset of the rows of a CSV file load it's likely that the full file is currently too big for Grid studio or possibly the rows you didn't load contain some sort of problematic character sequence that is causing escaping issues.

**Comment by MortyDai** [comment]
> 需要给csv文件赋予读取的权限，才能成功。
你好，请问如何给csv文件赋予读取权限呢？

**Comment by MortyDai** [comment]
> 需要给csv文件赋予读取的权限，才能成功。

你好，请问如何给csv文件赋予读取权限呢？
