### ISSUE TITLE
Run run-manager-proxy.sh: Permission denied

### ISSUE THREAD

**Issue by SherlockLiang** [ricklamers/gridstudio#33]
Hi dear,

New for docker and grid studio, The error msg shows as below after running ./run.sh:
bash: run-manager-proxy.sh: Permission denied

Please help to give me some advice! thx!

**Comment by ricklamers** [comment]
On what operating system are you using Docker?

**Comment by SherlockLiang** [comment]
CentOS Linux release 7.5.1804
Docker version 1.13.1

**Comment by ricklamers** [comment]
run-manager-proxy.sh is mounted in the Docker instance when you execute ./run.sh. Could you check the permissions on run-manager-proxy.sh on your CentOS Linux side?

**Comment by SherlockLiang** [comment]
I already add execute permission to the script run-manager-proxy.sh in CentOS.  But after adding --privileged option to the run.sh,  gridstudio is started up. I doubt that there is no permission to execute run-manager-proxy.sh in the docker container.

**Comment by ricklamers** [comment]
Since --privileged option made it work I'm thinking in your particular configuration the Docker container did not have access to the device that files were on. Closing this for now because it might be your particular configuration, if others have this - feel free to re-open this issue as it might indicate a broader problem that needs to be fixed.

**Comment by luxoracle** [comment]
I have the same problem when executing the run.sh under CentOS7.
![image](https://user-images.githubusercontent.com/41987613/62768740-1af5fe80-baca-11e9-817c-10c92b9a1541.png)

**Comment by ricklamers** [comment]
@luxoracle It's probably because you're running as root, so the files on the filesystem in the git repository will be owned by root. Try cloning as a regular user or try --priviliged in the docker run command.

**Comment by luxoracle** [comment]
I modified the run.sh file by adding '--privileged=true' to every docker run command line and it worked. Thank you.

**Comment by ricklamers** [comment]
@luxoracle glad it worked!
