### ISSUE TITLE
Troubleshooting(Help Needed): Not responding? 

### ISSUE THREAD

**Issue by Super-Gil** [ricklamers/gridstudio#34]
I am using Ubuntu 18.04LTS. Docker is already configured and updated to the newest version.
Using AWS EC2 instance.
I am encountering the problem that the process never stops... I tried to run HelloWorld but it keeps on computing for more than 10 mins and it's still computing. Need some help!
![Uploading snip.png…]()
![Uploading snip2.png…]()

**Comment by Super-Gil** [comment]
![snip](https://user-images.githubusercontent.com/41502813/62339893-31bbb480-b510-11e9-9f70-10a741e1169b.png)
![snip2](https://user-images.githubusercontent.com/41502813/62339894-34b6a500-b510-11e9-97b7-12c14de437c4.png)

**Comment by ricklamers** [comment]
The output of the log doesn't show anything out of the ordinary to me. The no uuid part always shows when you try to create a new workspace.

Could you show the error (that I think you're getting) on Google Chrome console? I feel like you might not have opened port 4430 on the AWS instance.

**Comment by Super-Gil** [comment]
Ah I don't know why but it's working now. That's magical! Maybe it's the problem with my Chrome. It is all fine using Firefox. Thanks for the help. Your development is really useful and saved me a lot of time switching from Excel to python. Great thanks!

**Comment by ricklamers** [comment]
Glad you're helped by the project!
