### ISSUE TITLE
bash: run.sh: command not found

### ISSUE THREAD

**Issue by lllsoft** [ricklamers/gridstudio#35]
windows  Git-2.22.0-64-bit
bash: run.sh: command not found

**Comment by yfnjupt** [comment]
I met with the same problem. I think it may be that there should be "docker" installed on your computer.

**Comment by ricklamers** [comment]
Make sure that you are inside the directory cloned git repository. What do you see if you type `ls`?

**Comment by cswxin** [comment]
install window-docker in your computer and make sure the line break is using Unix(LF) mode

**Comment by ricklamers** [comment]
Feel free to open this issue if you can't get it to work.
