### ISSUE TITLE
How is the limit of opening CSV file?

### ISSUE THREAD

**Issue by RyuAsuka** [ricklamers/gridstudio#37]
My CSV file contains about 700,000 rows x 61 columns (57 MB). And it cannot be opened in gridstudio, even my computer (8GB RAM running Ubuntu 18.04) stopped response. Can this software open large file? But the file can be directly imported using Pandas in Python.

**Comment by ricklamers** [comment]
HI RyuAsuka, at the moment this would entail creating approx 42M structs in Grid studio in the Go codebase. At the moment, I don't think the back-end is optimized enough to handle such a high amount of data. What I would recommend in the meantime is to read in the CSV in Python in Pandas and do your operations on the dataframe. You could still use the sheet for a part of the data or summaries of it.
