### ISSUE TITLE
''cd gridstudio && ./run.sh''failed with bash

### ISSUE THREAD

**Issue by whuNatsume** [ricklamers/gridstudio#38]
![image](https://user-images.githubusercontent.com/42495140/62521249-d8ca8400-b861-11e9-8ead-cf35fc6b245e.png)

**Comment by Nicersmeng** [comment]
same problem，It seem lack of docker installation

**Comment by wc411421** [comment]
you need install docker before

**Comment by ricklamers** [comment]
Install Docker from their website first: https://docs.docker.com/install/
