### ISSUE TITLE
File-Load CSV doesn't work

### ISSUE THREAD

**Issue by mf1633012** [ricklamers/gridstudio#39]
I have install this tool successfully, but when I click the button "File-Load CSV", Nothing happen.  The button only worked is Help-Documentation&Slack community. What's wrong with me?

**Comment by wc411421** [comment]
this problem also happens to me, and when i run the python code, it shows "Computing, please be patient"

**Comment by wc411421** [comment]
there are screenshot of my first and second excution
![1](https://user-images.githubusercontent.com/24862284/62540928-4939cb00-b88b-11e9-8263-c16a3d248bff.jpg)
![2](https://user-images.githubusercontent.com/24862284/62540951-548cf680-b88b-11e9-90c0-e676ee2000d3.jpg)

**Comment by ricklamers** [comment]
When you install Git for Windows make sure you select "checkout files as is" given the warning 
`run-manager-proxy.sh: line 3: $'\r':  command not found` makes me suspect that the files in the Grid studio repository have been converted to Windows line endings.

Try re-installing Git for Windows and cloning the repository again.

**Comment by ricklamers** [comment]
> I have install this tool successfully, but when I click the button "File-Load CSV", Nothing happen. The button only worked is Help-Documentation&Slack community. What's wrong with me?

This might actually be a different problem than what @wc411421 is experiencing. How big is the CSV file that you're uploading? If it's not private - could you link it? Or at least part of it so I can verify it's working on my end.

**Comment by mf1633012** [comment]
My problem is just cannot upload CSV file, nothing appear after clicking the button "Load CSV".

**Comment by wc411421** [comment]
I re-install git for windows and clone the repository again. This time there is no warning, but the buttons still does not work. 

The following is contents that my developer tools show, and you can see that there are only several menus listed, with no links. I am not so similar with go and don't know what happened.

Thanks for your reply.

![1](https://user-images.githubusercontent.com/24862284/62600964-d1b77a80-b922-11e9-9014-5e8215ccffb2.jpg)

**Comment by ricklamers** [comment]
@wc411421 I see that in your screenshot you're not using Google Chrome or Firefox, but are using Edge. It is not well tested in Edge. In your screenshot I see you get 4 errors - those will likely explain why it is not working. Please try Google Chrome first and see if it works.
