### ISSUE TITLE
Click error

### ISSUE THREAD

**Issue by bingheGT** [ricklamers/gridstudio#40]
When I selected one cell, if I click another cell, the cell selected previous will get the wrong content.

**Comment by ricklamers** [comment]
Could you post a screenshot or screen recording of the issue? Which browser are you using?

**Comment by tandelin1** [comment]
我这边没有遇到这个错误，目前来看，火狐和谷歌还是很友好的

**Comment by ricklamers** [comment]
Only English in GitHub issues please - hope you understand.

**Comment by ricklamers** [comment]
Inactivity close, feel free to re-open.
