### ISSUE TITLE
line 5: docker: command not found

### ISSUE THREAD

**Issue by zuogeov** [ricklamers/gridstudio#42]
when run "./run.sh", it gives me this:

$ cd gridstudio && ./run.sh
./run.sh: line 5: docker: command not found
./run.sh: line 11: docker: command not found

and I went to http://127.0.0.1:8080, I got can't reach this page, how can I fix the issue? Thank you!

**Comment by himsn** [comment]
I have the same problem too.

**Comment by huanshuer** [comment]
I have the same problem too.

**Comment by SaviorWu** [comment]
I have the same problem too. +1

**Comment by huanshuer** [comment]
maybe  we should install docker

**Comment by wuyi901005** [comment]
I fix it.  just install docker and make sure its running。

**Comment by huanshuer** [comment]
docker for windows?

**Comment by DolphinC** [comment]
I have the same problem too. what is docker?

**Comment by orangetcy** [comment]
> I have the same problem too. what is docker?

Baidu or Google is great thing.

**Comment by SaviorWu** [comment]
> I have the same problem too. +1 i'm mac10.14.6

here is docker http://mirrors.aliyun.com/docker-toolbox/mac/docker-for-mac/stable/ download it and install then fix it
