### ISSUE TITLE
After installing docker,i still cannot reach http://127.0.0.1:8080,

### ISSUE THREAD

**Issue by Twopence16** [ricklamers/gridstudio#43]
when run "./run.sh", it gives me this:
![image](https://user-images.githubusercontent.com/51435568/62589478-fcdaa380-b8fb-11e9-8e9d-0cc13ace50d3.png)

then I went to http://127.0.0.1:8080, I still can't reach this page, how can I fix the issue? Thank you!

**Comment by ricklamers** [comment]
Is the container listed under `docker containt ls`?

**Comment by Twopence16** [comment]
> iner
![image](https://user-images.githubusercontent.com/51435568/62612544-287c7e80-b93a-11e9-9251-5e3b12afb13a.png)
this is image list and container list

**Comment by ricklamers** [comment]
Looks like it exited with an error code. `docker container logs` should give you details as to why.

**Comment by Twopence16** [comment]
yes, log told me docker cannot find run-manager-proxy.sh,but run-manager-proxy.sh is in content
![image](https://user-images.githubusercontent.com/51435568/62612925-10592f00-b93b-11e9-9c77-1e7c65b718fa.png)

![image](https://user-images.githubusercontent.com/51435568/62613123-6e861200-b93b-11e9-86af-9c5972fe725f.png)

**Comment by ricklamers** [comment]
Someone has run into this earlier #33, it's likely related to permissions on the mounted directory. Could you try running the docker command in the .sh file with --privileged?

**Comment by Twopence16** [comment]
Could you give more details on how to run the command with '--privileged'?

**Comment by ricklamers** [comment]
Please refer to https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by Twopence16** [comment]
> Please refer to https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
Yes,I remove container and rewrite run.sh below and it really works.Thank you,rick!
![image](https://user-images.githubusercontent.com/51435568/62671504-beabb580-b9c9-11e9-9d0d-615972f9dff1.png)

**Comment by ricklamers** [comment]
Good to hear, it's not always easy to get the permissions right with containers :)
