### ISSUE TITLE
Not working on Win7 running Docker Toolbox

### ISSUE THREAD

**Issue by sinablk** [ricklamers/gridstudio#47]
I successfully downloaded the docker image and it shows in `docker images`. But I get the following error after ` ./run.sh` on Git Bash for Win7 running Docker Toolbox:

```bash
$ ./run.sh
Error response from daemon: No such container: gridstudio
Error: failed to start containers: gridstudio
```

I can run the container using `docker run ricklamers/gridstudio:release` which gives the following output (same as `docker logs <CONTAINER>`:
![Screenshot_1](https://user-images.githubusercontent.com/20431332/62620230-02e97800-b92e-11e9-9563-736f8579a674.png)

Since I'm running Docker Toolbox, my default IP is `192.168.99.100`, but I get a "Unable to connect" error when visiting http://192.168.99.100:8080.

And here's the output from `docker container ls`:
![Screenshot_2](https://user-images.githubusercontent.com/20431332/62620428-8a36eb80-b92e-11e9-91d8-a4e541e2c6bb.png)

Also, the folder is located in `C:\Users\sina\repos\gridstudio`.

**Comment by ricklamers** [comment]
Could you run destroy.sh and run.sh consecutively? Perhaps you could modify the run.sh file to have the full image name as in your self run command `ricklamers/gridstudio:release`.

Haven't worked with Docker Toolkit so I'm not really familiar with the differences. When you run your own command that seems to run the server you're not forwarding the ports so that's why it's failing.

**Comment by sinablk** [comment]
Well, the main problem was finding out to which ports it was actually forwarding. I executed `docker run -d -p 8080 ricklamers/gridstudio:release` and used Kitematic (which comes with Docker Toolbox) to look at my active containers. I used the Web Preview tab to open the app:
![Screenshot_2](https://user-images.githubusercontent.com/20431332/62700504-5c69a980-b9f7-11e9-82ce-11dc9008b9b1.png)


This opens up `192.168.99.100` with a random port and takes me to the admin page. I can successfully login to the dashboard, but as soon as I create or open a workspace, it gives me this error:
![Screenshot_1](https://user-images.githubusercontent.com/20431332/62700422-1c0a2b80-b9f7-11e9-9cd0-47a473e09b15.png)


Here's output from `docker container ls`:
![Screenshot_3](https://user-images.githubusercontent.com/20431332/62700765-f9c4dd80-b9f7-11e9-857c-e2e709efa380.png)


Checking the logs, you can see there's a `runtime error`:
![Screenshot_4](https://user-images.githubusercontent.com/20431332/62701294-29281a00-b9f9-11e9-88ad-9217b7251473.png)

**Comment by ricklamers** [comment]
In the run.sh the Docker command shows the flag -p 8080:8080 -p 4430:4430 for port forwarding. That should also work in your case.

**Comment by sinablk** [comment]
Yup, that does work. But I still get the "Lost connection to server. Redirect to dashboard?" error after opening workspace. Even when I hit "Cancel", I still cannot operate the sheet, interpreter, terminal, or anything.

**Comment by ricklamers** [comment]
It disconnects if it cannot establish a connection to the websocket server on port 4430. It appears this connection can still not be made in your setup.

Docker Toolbox is not intended to be supported - i.e. feel free to try and make it work but I'm not able to give you support on how to make it work.

**Comment by nanayuri** [comment]
hello, you may try to use "docker run --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release" to run the gridsutdio.

**Comment by wanmeow** [comment]
@nanayuri your answer actually helps! Thank you so much
