### ISSUE TITLE
It soon poped out "lost connection to server redirect to dashboard"after  the webpage being loaded 

### ISSUE THREAD

**Issue by sichaoguo21** [ricklamers/gridstudio#51]
- _OS_: Win7 professional sp1 

- _Docker_ installed with **DockerToolbox-18.03.0-ce.exe**

- _Gridstudio_ running with **kitematic**

![issue2](https://user-images.githubusercontent.com/3440990/62674008-169aea00-b9d3-11e9-84d2-43538a798bf6.PNG)

It soon poped out **"lost connection to server redirect to dashboard"** after  the webpage being loaded , no matter how many times I tried.
![issue1](https://user-images.githubusercontent.com/3440990/62670426-c8cbb500-b9c5-11e9-8b49-d0ec91c65ae4.PNG)

What's wrong might it be?

Network communication could be route traced as below:
![issue3](https://user-images.githubusercontent.com/3440990/62688431-6b525b00-b9fb-11e9-8723-2141844deff5.PNG)

**Comment by nanayuri** [comment]
I just installed Docker 18.03.0-ce, after running the gridstudio I met the same error....

**Comment by tandelin1** [comment]
这个问题是因为没有保存存储空间造成的。尝试一下操作试试
![image](https://user-images.githubusercontent.com/37764776/62689969-6216bd80-b9fe-11e9-8950-17773ee8ecdd.png)

**Comment by ricklamers** [comment]
If you use Docker Toolbox instead of ./run.sh - make sure to forward both port 8080 and 4430.

**Comment by sichaoguo21** [comment]
@tandelin1 求教，具体咋操作？啥叫没有保存存储空间。

**Comment by sichaoguo21** [comment]
@ricklamers sorry, I don't understand, how can I configure that in dock toolbox?

**Comment by tandelin1** [comment]
https://blog.csdn.net/tandelin/article/details/98944427




------------------ 原始邮件 ------------------
发件人: "ChaosSin.God"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午8:30
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送: "此后行"<1525859926@qq.com>;"Mention"<mention@noreply.github.com>;
主题：  Re：[ricklamers / gridstudio]网页加载后很快就出现了“丢失连接toserver重定向到仪表板”（＃51）




@ricklamers抱歉，我不明白，如何在Dock工具箱中配置？
  
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by sichaoguo21** [comment]
> 
> 
> 这个问题是因为没有保存存储空间造成的。尝试一下操作试试
> ![image](https://user-images.githubusercontent.com/37764776/62689969-6216bd80-b9fe-11e9-8950-17773ee8ecdd.png)


我试了一下，并非这个原因。这个弹窗是新建workspace一加载网页就弹出来的，也就是一显示就断了通讯，后面点save workspace毫无反应，状态显示只是停在saving workspace。
![issue4](https://user-images.githubusercontent.com/3440990/62756335-ef631c00-baa9-11e9-8f3d-0bcefbe8d90d.PNG)

**Comment by sichaoguo21** [comment]
@tandelin1 帮忙看下博主回复的原因，什么两个端口都要转发，应该怎么设置，谢谢！

**Comment by tandelin1** [comment]
你需要描述的是：你用的什么系统，目前是什么问题，你出现的问题是服务器连接丢失,应该是网络的问题。你是否仔细检查了你的网络，能否ping其它网络呢？


What you need to describe is: what system you use, what problems are currently, what problems you have is the loss of server connections, should be the problem of the network. Have you checked your network carefully? Can you Ping other networks?


------------------ 原始邮件 ------------------
发件人: "ChaosSin.God"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 中午1:36
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送: "此后行"<1525859926@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ricklamers/gridstudio] It soon poped out "lost connection toserver redirect to dashboard"after  the webpage being loaded  (#51)




@tandelin1 帮忙看下博主回复的原因，什么两个端口都要转发，应该怎么设置，谢谢！

**Comment by sichaoguo21** [comment]
> 
> 你需要描述的是：你用的什么系统，目前是什么问题，你出现的问题是服务器连接丢失,应该是网络的问题。你是否仔细检查了你的网络，能否ping其它网络呢？ What you need to describe is: what system you use, what problems are currently, what problems you have is the loss of server connections, should be the problem of the network. Have you checked your network carefully? Can you Ping other networks?
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ChaosSin.God"<notifications@github.com>; 发送时间: 2019年8月9日(星期五) 中午1:36 收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>; 抄送: "此后行"<1525859926@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [ricklamers/gridstudio] It soon poped out "lost connection toserver redirect to dashboard"after the webpage being loaded (#51) @tandelin1 帮忙看下博主回复的原因，什么两个端口都要转发，应该怎么设置，谢谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
开头有说明，和截图。

**Comment by sichaoguo21** [comment]
> 
> 
> If you use Docker Toolbox instead of ./run.sh - make sure to forward both port 8080 and 4430.
@ricklamers 
I tried to run gridstudo through ./run.sh, but still cannot open localhost:8080, the container info tells that:
![issue7](https://user-images.githubusercontent.com/3440990/62758796-03ab1700-bab2-11e9-974a-93b815773f35.PNG)

**Comment by ricklamers** [comment]
Could you try http://127.0.0.1:8080 instgead of localhost - it probably won't matter but it's worth a shot.

**Comment by sichaoguo21** [comment]
> 
> 
> Could you try http://127.0.0.1:8080 instead of localhost - it probably won't matter but it's worth a shot.

I tried, but it's the same result---ERR_CONNECTION_REFUSED

**Comment by ricklamers** [comment]
@sichaoguo21 Could you show the log of the container? `docker logs <containerid>`

**Comment by jeremydouglass** [comment]
I got these same errors on macOS 12 when I try to run gridstudio directly from dockerhub.

FYI, I *believe* that at present the container isn't designed to be run from Dockerhub -- instead, it is designed for you to build the container locally from the Dockerfile in a clone of the github repo, with persistent data in a volume on the local host.

**Comment by wookim789** [comment]
Hello. 
I well uesd grid studio but i got some same isue too.

This is my env.
window10 > Vmware :ubuntu 18 > docker container 

When i  acess in Vmware(ubuntu) to 127.0.0.1:8080,   it is work.

And at the host window, i could acess 127.0.0.1:8080 or vmware Ip:8080 it was work.

When i give havy work to grid after, it is not work in host window.

So to sum it up, 
Every env could acess to login page and worksapce, but could'nt acess to the grid sheet page except Vmware.  
 
When i access in host window 127.0.0.1:8080 or vmware ip :8080 
could log in and go into workspace. But when I go to the workspace,
![image](https://user-images.githubusercontent.com/38445103/63335684-c7f93280-c378-11e9-87e6-c68e0793ba77.png)

like this, error occured.

And, the console in vmware that run the run.sh file print like this.  
![image](https://user-images.githubusercontent.com/38445103/63335746-e101e380-c378-11e9-90d6-fe4aff3b9b6f.png)

And back to the grid studio, 
when i click the alter box btn, the console(sh run.sh) print the log like this.

No uuid found, creating new WorkSession and processes
Create users session with UUID: 4474256a-f8e4-4e46-8ac3-618541dbf701.
5 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/08/20 18:39:06 http: panic serving 192.168.4.74:53404: runtime error: invalid memory address or nil pointer dereference
goroutine 610 [running]:
net/http.(*conn).serve.func1(0xc00006ad20)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x890ee0, 0xe35fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc0003c71ce, 0x24, 0xc000060e10, 0xc000060e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98bc40, 0xc00032f880, 0xc00041c700)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00000e460, 0x98bc40, 0xc00032f880, 0xc00041c700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe71d60, 0x98bc40, 0xc00032f880, 0xc00041c700)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000066d00, 0x98bc40, 0xc00032f880, 0xc00041c700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00006ad20, 0x98c440, 0xc000394b40)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
Tried destroying session 4474256a-f8e4-4e46-8ac3-618541dbf701, but sessions not in active usersessions.
4 user sessions active.

**Comment by wookim789** [comment]
Oh i solve this problem. 
When I port forwarding in vmware,
Just did 8080 port. I did'nt port forwading  the 4430.
So When i port forwarding the 4430: 4430 in Vmware It work in host window!
thanks.

**Comment by nicozhang** [comment]
> If you use Docker Toolbox instead of ./run.sh - make sure to forward both port 8080 and 4430.
> @ricklamers
> I tried to run gridstudo through ./run.sh, but still cannot open localhost:8080, the container info tells that:
> ![issue7](https://user-images.githubusercontent.com/3440990/62758796-03ab1700-bab2-11e9-974a-93b815773f35.PNG)

确实是端口的问题，除了 8080 有打开，4430 也要打开

both 8080 and 4430 should be forwarded

**Comment by linweifu** [comment]
docker 容器的端口映射不能修改，必须要8080->8080 4430->4430
