### ISSUE TITLE
Can the storage space save the picture as well?

### ISSUE THREAD

**Issue by tandelin1** [ricklamers/gridstudio#52]
I output the data to the excel table and find that the result is acceptable.This is how I operate:
sql="select ID,type_NO from f_personal_info where rownum<5"
data = pd.read_sql(sql,connection)
print(data)
data.head(n=2)
sheet("A",data,headers=True)

![image](https://user-images.githubusercontent.com/37764776/62690385-334d1700-b9ff-11e9-97b5-2a8b523a67ec.png)

However, when the workspace I saved was reopened, the image data did not exist.

How can this be solved?

Thank you very much

**Comment by ricklamers** [comment]
You can save the Plotly interactive plots with the disk icon. You save it directly to your device from the browser - if you want it in your spreadsheet environment. Simply upload the file there via the menu,

**Comment by tandelin1** [comment]
thanks,I think this picture will still exist after landing in this space. The effect of the dashboard is similar to that of Tableau. Can it be developed later?


------------------ 原始邮件 ------------------
发件人: "Rick Lamers"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 凌晨4:46
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送: "此后行"<1525859926@qq.com>;"Author"<author@noreply.github.com>;
主题：  Re：[ricklamers / gridstudio]存储空间可以保存图片吗？（＃52）




您可以使用磁盘图标保存Plotly交互式图。您可以通过浏览器将其直接保存到设备中 - 如果您希望在电子表格环境中使用它。只需通过菜单上传文件，
  
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。
