### ISSUE TITLE
What contribution can I make?

### ISSUE THREAD

**Issue by tandelin1** [ricklamers/gridstudio#53]
I am a student in Xi'an, China. When I saw your open source project, I studied and installed it in the first time. It was very interesting, but I don't know if I can help you. I studied statistics, and the tool I was good at was R language.

If you have any place where you need me, please feel free to tell me. I have plenty of time. I hope this tool can be used more in China.

**Comment by ricklamers** [comment]
Hi @tandelin1,

Welcome to the project - glad you liked it.

I've seen that some people are interested in support for foreign character sets to support i.e. the Chinese or Japanese language. You could try to find which changes to the codebase are necessary to make it work.

Does that sound interesting?

**Comment by tandelin1** [comment]
Okay, that's great. I'm glad.

**Comment by ricklamers** [comment]
Inactivity close, feel free to re-open.
