### ISSUE TITLE
Could pls give a step by step guide?

### ISSUE THREAD

**Issue by jinwzhang** [ricklamers/gridstudio#54]
I am using Pycharm and just cloned this project. But I can't find a way to start using it.

Which scripts should I run or command to input in where to get the grid to pop out like using Jupter (aka: command> Juputer notebook > then the page came out)? 

Sorry for this stupid question since I just know this tool via a article. Thanks!

**Comment by ricklamers** [comment]
Please read https://github.com/ricklamers/gridstudio/wiki/Installation and open issues only with specific issues :)
