### ISSUE TITLE
Lost connection to the server. Redirect to dashboard?

### ISSUE THREAD

**Issue by zhangga1302** [ricklamers/gridstudio#55]
centos7,docker18.09.7

**1、installed the grid studio;success**

**2、user the root account run the cmd：./run.sh**

> [root@publicmariadb gridstudio]# ./run.sh 
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
Hashed PW: 19yxYLFN-1h1mow8cpqDqLlgsHo=

**3、open　chrom http://127.0.0.1:8080**
**4、login：admin/admin
5、for 5-10 seconds,pop the eror "Lost connection to the server. Redirect to dashboard?"**Lost connection to the server. Redirect to dashboard?

**Comment by ricklamers** [comment]
Could you post a screenshot of the JavaScript console / Chrome dev tools Network tab?

Do you do anything in the app or does it just sit idling?

I'm thinking it's unable to connect to port 4430 on 127.0.0.1 because the websocket connection is on that port and it dropping or timing out would cause the error message you're providing.

**Comment by ricklamers** [comment]
Inactivity close, feel free to re-open.

**Comment by tangdaniu** [comment]
i am trying to run gridstudio on chromebook (embedded linux), also have this issue.

**Comment by nicozhang** [comment]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/1912794/67634661-e55af780-f8f9-11e9-9a1f-961dbee72f18.png">

This js file 404

**Comment by ricklamers** [comment]
Could you share some more details about your run environment?

Are you using Docker? If so, which version? Also, could you post the Docker logs of the container?

How did you start Grid Studio? Which command?

Thanks in advance ; )

**Comment by nicozhang** [comment]
> Could you share some more details about your run environment?
> 
> Are you using Docker? If so, which version? Also, could you post the Docker logs of the container?
> 
> How did you start Grid Studio? Which command?
> 
> Thanks in advance ; )

This js file is not the main problem for lost connection error :)  
The 4430 is not forwarded

But the js file 404 still exists.

--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
Hashed PW: 19yxYLFN-1h1mow8cpqDqLlgsHo=
Login, found user matching hashed PW.
No uuid found, creating new WorkSession and processes
Create users session with UUID: ad94beea-3e26-4117-9876-32fb181cf724.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/10/27 12:16:18 http: panic serving 172.17.0.1:38382: runtime error: invalid memory address or nil pointer dereference
goroutine 236 [running]:
net/http.(*conn).serve.func1(0xc000139ea0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x8918c0, 0xe37fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc00043a48e, 0x24, 0xc000072e10, 0xc000072e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98c960, 0xc000143960, 0xc00040ee00)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00007a440, 0x98c960, 0xc000143960, 0xc00040ee00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe73d60, 0x98c960, 0xc000143960, 0xc00040ee00)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00007cb60, 0x98c960, 0xc000143960, 0xc00040ee00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000139ea0, 0x98d160, 0xc00022db00)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
Tried destroying session ad94beea-3e26-4117-9876-32fb181cf724, but sessions not in active usersessions.
0 user sessions active.
Opening UUID: ad94beea-3e26-4117-9876-32fb181cf724
Create users session with UUID: ad94beea-3e26-4117-9876-32fb181cf724.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/10/27 12:18:48 http: panic serving 172.17.0.1:38590: runtime error: invalid memory address or nil pointer dereference
goroutine 410 [running]:
net/http.(*conn).serve.func1(0xc000138320)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x8918c0, 0xe37fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc00011784e, 0x24, 0xc000072e10, 0xc000072e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98c960, 0xc00011eee0, 0xc000156200)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00007a440, 0x98c960, 0xc00011eee0, 0xc000156200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe73d60, 0x98c960, 0xc00011eee0, 0xc000156200)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00007cb60, 0x98c960, 0xc00011eee0, 0xc000156200)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000138320, 0x98d160, 0xc00008c780)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
Tried destroying session ad94beea-3e26-4117-9876-32fb181cf724, but sessions not in active usersessions.
0 user sessions active.
Opening UUID: ad94beea-3e26-4117-9876-32fb181cf724
Create users session with UUID: ad94beea-3e26-4117-9876-32fb181cf724.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/10/27 12:19:28 http: panic serving 172.17.0.1:38648: runtime error: invalid memory address or nil pointer dereference
goroutine 432 [running]:
net/http.(*conn).serve.func1(0xc00007efa0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x8918c0, 0xe37fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc0000e684e, 0x24, 0xc000072e10, 0xc000072e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98c960, 0xc000120380, 0xc000056700)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00007a440, 0x98c960, 0xc000120380, 0xc000056700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe73d60, 0x98c960, 0xc000120380, 0xc000056700)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00007cb60, 0x98c960, 0xc000120380, 0xc000056700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00007efa0, 0x98d160, 0xc00008ce40)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
Tried destroying session ad94beea-3e26-4117-9876-32fb181cf724, but sessions not in active usersessions.
0 user sessions active.
No uuid found, creating new WorkSession and processes
Create users session with UUID: a5d86d9f-e841-41d7-a757-9d4a2fb0a8e5.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/10/27 12:20:08 http: panic serving 172.17.0.1:38806: runtime error: invalid memory address or nil pointer dereference
goroutine 602 [running]:
net/http.(*conn).serve.func1(0xc000139cc0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x8918c0, 0xe37fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc0001b808e, 0x24, 0xc000072e10, 0xc000072e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98c960, 0xc00011f5e0, 0xc000279200)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00007a440, 0x98c960, 0xc00011f5e0, 0xc000279200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe73d60, 0x98c960, 0xc00011f5e0, 0xc000279200)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00007cb60, 0x98c960, 0xc00011f5e0, 0xc000279200)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000139cc0, 0x98d160, 0xc00022ccc0)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
Opening UUID: ad94beea-3e26-4117-9876-32fb181cf724
Create users session with UUID: ad94beea-3e26-4117-9876-32fb181cf724.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
Opening UUID: ad94beea-3e26-4117-9876-32fb181cf724
Opening UUID: ad94beea-3e26-4117-9876-32fb181cf724

**Comment by ricklamers** [comment]
Do you use the run.sh file from the Git repo? It should forward 4430

**Comment by nicozhang** [comment]
> Do you use the run.sh file from the Git repo? It should forward 4430
> […](#)
Yes I have already fixed this problem.
But I meet another one. How could I install packages? connect docker terminal and run pip  ?

**Comment by ricklamers** [comment]
Good to hear it was fixed by forwarding. You can also use pip install form
the terminal within Grid Studio. Alternatively, you could connect to Docker
and run pip.

Op zo 27 okt. 2019 om 14:30 schreef nicozhang <notifications@github.com>:
