### ISSUE TITLE
pd.read_csv doesn't work

### ISSUE THREAD

**Issue by Twopence16** [ricklamers/gridstudio#56]
Hi,rick.I fail to use `pd.read_csv` to load a file in gridstudio though I can load the same file in spyder with same path.  Here is error log
![image](https://user-images.githubusercontent.com/51435568/62771860-be4a1200-bad0-11e9-902e-8cc6f0179351.png).

**Comment by ricklamers** [comment]
When loading files from disk, note that you are in a separate Docker environment. 

In the Python process use: `os.chdir("/home/user/...")` to set the working directory of the Python process to the right directory.

Currently, file upload to the Docker environment is not working properly. To get the files in the Docker container copy them to the mounted user directory directly. (This is the grid-app/proxy/userdata/ directory).
