### ISSUE TITLE
Win7 | bash:run-manager-proxy.sh: No such file or directory

### ISSUE THREAD

**Issue by livingworld** [ricklamers/gridstudio#57]
### background

operating system：win7
docker: DockerToolbox-18.03.0-ce
virtual machine: VirtualBox v5.2.8 r121009

### problems

At first I had a problem with lowercase , so I changed it to:

```
WIN_PWD=$pwd
```
But there's a problem with the path. Then the following parts were changed：

```
docker run --name=gridstudio --rm=false -v $WIN_PWD/grid-app:/home/source -v $WIN_PWD/grid-app/proxy/userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
```

The problem disappeared, but then came up with the following problems:

>bash:run-manager-proxy.sh: No such file or directory

In Oracle VM Virtual Box Manager, I set up a shared folder and chose a fixed allocation path, the gridstudio storage location, but the problem is still there. Maybe I set it incorrectly.

I read a lot of information, such as [run-manager-proxy.sh missing after docker run command · Issue #48](https://github.com/ricklamers/gridstudio/issues/48), but I still haven't solved the problem.

I'm here to ask for your help. Thank you!

**Comment by ricklamers** [comment]
It looks like the mounting of the folders is not succeeding, this part of the command: 

`$WIN_PWD/grid-app:/home/source -v $WIN_PWD/grid-app/proxy/userdata:/home/userdata`

Could you output what

`echo $WIN_PWD` outputs if you add that to the bash file? (After WIN_PWD is assigned, but before the Docker command).

**Comment by livingworld** [comment]
@ricklamers 

I changed the directory where the code was stored to disk d.

The catalogue is as follows:
    
    D:\gridstudio

Although I did not modify the run.sh file, I did not encounter a lowercase error again.

Then, Enter commands：

    $WIN_PWD/grid-app:/home/source -v $WIN_PWD/grid-app/proxy/userdata:/home/userdata

output:

>bash: /grid-app:/home/source: No such file or directory

Then, add the following command before the Docker command

     echo $WIN_PWD

Then, run the following command:

    ./run.sh

output:

>/d/gridstudio
>bash: run-manager-proxy.sh: No such file or directory

**Comment by livingworld** [comment]
@ricklamers 

I changed the directory where the code was stored to disk d.

The catalogue is as follows:
    
    D:\gridstudio

Although I did not modify the run.sh file, I did not encounter a lowercase error again.

Then, Enter commands：

    $WIN_PWD/grid-app:/home/source -v $WIN_PWD/grid-app/proxy/userdata:/home/userdata

output:

>bash: /grid-app:/home/source: No such file or directory

Then, add the following command before the Docker command

     echo $WIN_PWD

Then, run the following command:

    ./run.sh

output:

>/d/gridstudio
>D:\Program Files\Docker Toolbox\docker.exe:  Error response from daemon:  invalid mode: /home/source

Add the following command before the Docker command

    WIN_PWD=$(echo $WIN_PWD | sed -r 's/[/]+/\\/g')
    WIN_PWD=$(echo $WIN_PWD | sed -r 's/\\([a-z])\\+/\U\1:\\/g')
    echo $WIN_PWD\\grid-app:/home/source

Then, run the following command:

    ./run.sh

output:

>/d/gridstudio
>D:\gridstudio\grid-app:/home/source
>D:\Program Files\Docker Toolbox\docker.exe:  Error response from daemon:  invalid mode: /home/source

## code

    #!/usr/bin/env bash

    if [[ "$OSTYPE" == "msys" ]]; then

    	if [ ! "$(docker ps -a | grep gridstudio)" ]; then

    		WIN_PWD=$PWD
    		echo $WIN_PWD
    		WIN_PWD=$(echo $WIN_PWD | sed -r 's/[/]+/\\/g')
    		WIN_PWD=$(echo $WIN_PWD | sed -r 's/\\([a-z])\\+/\U\1:\\/g')
    		echo $WIN_PWD\\grid-app:/home/source
    		docker run --name=gridstudio --rm=false -v $WIN_PWD\\grid-app:/home/source -v $WIN_PWD\\grid-app\\proxy\\userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
    	else
    		echo "gridstudio container detected - starting container - want to do a full restart? Run destroy.sh first."
    		docker start gridstudio
    	fi
    else
    	if [ ! "$(docker ps -a | grep gridstudio)" ]; then
    		docker run --name=gridstudio --rm=false -v $PWD/grid-app:/home/source -v $PWD/grid-app/proxy/userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
    	else
    		echo "gridstudio container detected - starting container - want to do a full restart? Run destroy.sh first."
    		docker start gridstudio
    	fi
    fi

**Comment by ricklamers** [comment]
@livingworld I've Googled around a bit and I think it's because of Docker Toolbox and how it handles paths differently to regular Docker:

https://nickjanetakis.com/blog/docker-tip-66-fixing-error-response-from-daemon-invalid-mode

Relevant comment: 

> It was because I installed Docker Toolbox next to Docker or Windows. After uninstall Docker Toolbox, the host_mnt prefix is no longer needed.

Please try it with normal Docker because Docker Toolbox isn't supported explicity.

**Comment by livingworld** [comment]
Change the following command:

    docker run --name=gridstudio --rm=false -v $WIN_PWD\\grid-app:/home/source -v $WIN_PWD\\grid-app\\proxy\\userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release

to:

    docker run --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release

This time, the code ran successfully.

**Comment by cherrylast** [comment]
> 
> 
> @ricklamers
> 
> Okay, thank you!
> 
> I found a way out here：[Not working on Win7 running Docker Toolbox · Issue #47 · ricklamers/gridstudio](https://github.com/ricklamers/gridstudio/issues/47)
> 
> I change the following command:
> 
> ```
> docker run --name=gridstudio --rm=false -v $WIN_PWD\\grid-app:/home/source -v $WIN_PWD\\grid-app\\proxy\\userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
> ```
> 
> to:
> 
> ```
> docker run --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
> ```
> 
> This time, the code ran successfully.

If you do this, I think maybe the userdata will be affected because you dont' mount the local file path. I put some data on the grid, then use file->export as csv, but nothing happened. I don't know where to find the csv file. Do you have this problem?

**Comment by cherrylast** [comment]
> 
> 
> @ricklamers
> 
> Okay, thank you!
> 
> I found a way out here：[Not working on Win7 running Docker Toolbox · Issue #47 · ricklamers/gridstudio](https://github.com/ricklamers/gridstudio/issues/47)
> 
> I change the following command:
> 
> ```
> docker run --name=gridstudio --rm=false -v $WIN_PWD\\grid-app:/home/source -v $WIN_PWD\\grid-app\\proxy\\userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
> ```
> 
> to:
> 
> ```
> docker run --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
> ```
> 
> This time, the code ran successfully.

Yes, thanks. I still have some doubts. If the path is not mounted by -v, is there anything that would be affected?

**Comment by ricklamers** [comment]
If you don't mount the path it doesn't use the latest source code from the master branch in the repository. The Docker instance is mostly a container for all dependencies while the actual source is in there, it's set up currently to use the code that comes from the mounted directory.

Does that make sense?

**Comment by ricklamers** [comment]
Without mounting the `userdata` directory the files are only persistent in the Docker container. If you were to delete the container you also lose all the `userdata` files.

**Comment by cherrylast** [comment]
> 
> 
> If you don't mount the path it doesn't use the latest source code from the master branch in the repository. The Docker instance is mostly a container for all dependencies while the actual source is in there, it's set up currently to use the code that comes from the mounted directory.
> 
> Does that make sense?

If I don't mount and I don't use the latest source code, then I'm only using the pulled release mirror? It seems to be working fine.

**Comment by ricklamers** [comment]
I've just updated Docker image to the latest stable release, so at the
moment there shouldn't be a difference!

Op ma 26 aug. 2019 om 11:38 schreef cherrylast <notifications@github.com>:
