### ISSUE TITLE
I cannot read data from spreadsheet with python script

### ISSUE THREAD

**Issue by hitachinsk** [ricklamers/gridstudio#59]
Hello, I'm a newcomer to this fantastic project, and I fill the A1: A7 grids with different data, and tried to write a python script to read the data from these grids. I wanted to assign the values to the `matrix` variable, so I wrote.
`matrix = sheet("A1:A3")`
But python raised an error which told me name `matrix` is not defined, maybe I'm not familiar with this software, and can anyone tell me how to fix this error? Thank you very much and I'm looking forward to your reply!

**Comment by ricklamers** [comment]
Hi @hitachinsk welcome to Grid studio - glad you like it.

Could you take a screenshot of your code? The code you post here is correct and should not give you an error.

**Comment by hitachinsk** [comment]
![gridStudioError](https://user-images.githubusercontent.com/34183663/62828623-771d6780-bc1d-11e9-87da-fdd46a864a7d.png)
Here is my screenshot, I really don't know how to fix this problem, I'm looking forward to your advise

**Comment by hitachinsk** [comment]
One more thing, my operating system is Ubuntu18.04, I installed anaconda in my computer, which can switch the version of python between 2.7 and 3.5. Can gridstudio support anaconda to change python's version?

**Comment by alecgirman** [comment]
It doesnn't say it anywhere but when you run a script, it runs whatever line youre on or if you have anything selected, then what you selected.  try selecting all of it and then running it.

**Comment by ricklamers** [comment]
@alecgirman is right. Have your tried selecting the code and pressing play (or Ctrl+Enter)?

**Comment by hitachinsk** [comment]
Thank you very much,  now the codes works well, I will spend more time exploring how to use this software,  maybe it will be a very powerful item for me in my work! @alecgirman @ricklamers
