### ISSUE TITLE
run in Ubuntu got error help，please!

### ISSUE THREAD

**Issue by xtuyaowu** [ricklamers/gridstudio#61]
![image](https://user-images.githubusercontent.com/20146795/62828810-738bdf80-bc21-11e9-9d5e-5f2549e0ff67.png)

**Comment by alecgirman** [comment]
You must have modified your version of the file by accident as [the one on this repo is correct](https://github.com/ricklamers/gridstudio/blob/master/grid-app/static/xterm/dist/main.js).

**Comment by ricklamers** [comment]
@xtuyaowu I think @alecgirman is right. It looks like your main.js is modified incorrectly/corrupted. Try re-installing by cloning the repository again. If you run into the same issue again after doing that feel free to open the ticket.
