### ISSUE TITLE
Security risks

### ISSUE THREAD

**Issue by alecgirman** [ricklamers/gridstudio#63]
Unfortunately, running Grid on a server or PC with those ports open to the public is a massive security risk.  

* Once setup initially, the security is limited to the access tokens, which are sent in plain text.  If somebody got them, they could just login from their PC with no problem.
  
  * And that is assuming they setup their account.  When using defaults, its worse.

* Once somebody is in the editor, they have access to the docker's bash and python access.  Remember docker only runs in exclusively sudo.

* If the user shares their OS filesystem with the Docker (or runs it natively), then bash and python (and anything else they install) have FULL access to the host OS and can do virtually anything.  For this, I'm gonna say that you **should not** share your filesystem with Docker.

**Comment by ricklamers** [comment]
@alecgirman Thanks for this contrib. I'll go into this in more detail soon.

I think in general at the moment security isn't where it's supposed to be. When you run Grid on your local machine don't make the ports publicly available.

What I've done for https://dashboard.gridstudio.io at the moment is that each instance runs on a virtual machine with only Grid studio on it (single user per VM) to somewhat mitigate the issues you mention.

**Comment by alecgirman** [comment]
Nevermind, closing this issue bc I'm stupid, didn't know anything about docker or Linux at the time.  I still don't know much about docker but iI know it should have no problems.for you.
