### ISSUE TITLE
Win7 | bash: run.sh: command not found

### ISSUE THREAD

**Issue by chenstarsQ** [ricklamers/gridstudio#65]
I have already installed Docker on my computer.

**Comment by chenstarsQ** [comment]
I downloaded the project as a zip and unzipped it, then ran ‘run.sh’ in git bash, then it prompts me “bash: run.sh: command not found ”
what should i do ？

**Comment by tandelin1** [comment]
You need to execute. / run.sh or sh run.sh


------------------ 原始邮件 ------------------
发件人: "Chen Star"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 下午2:44
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送：  “已订阅”<subscribed@noreply.github.com>;
主题：  Re：[ricklamers / gridstudio] Win7 | bash：run.sh：找不到命令（＃65）




我将项目作为zip下载并解压缩，然后在git bash中运行'run.sh'，然后它提示我“bash：run.sh：command not found” 
 我该怎么办？
  
- 
您收到此消息是因为您订阅了此主题。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by tandelin1** [comment]
You need to execute。/ run.sh或sh run.sh


------------------ 原始邮件 ------------------
发件人: "Chen Star"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 下午2:44
收件人: "ricklamers/gridstudio"<gridstudio@noreply.github.com>;
抄送：  “已订阅”<subscribed@noreply.github.com>;
主题：  Re：[ricklamers / gridstudio] Win7 | bash：run.sh：找不到命令（＃65）




我将项目作为zip下载并解压缩，然后在git bash中运行'run.sh'，然后它提示我“bash：run.sh：command not found” 
 我该怎么办？
  
- 
您收到此消息是因为您订阅了此主题。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by chenstarsQ** [comment]
Thank for you reply
But still can't work
-----------------------------
$ sh run.sh
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified.
C:\Program Files\Docker Toolbox\docker.exe: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?name=gridstudio: open //./pipe/docker_engine: The system cannot find the file specified..
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by pengpengtiaodexiaolu** [comment]
I guess I met the same problem with you. "Git Bash for Windows - Docker install" this means you should download the "git for windows" and Docker, then run git and docker at the same time.

**Comment by chenstarsQ** [comment]
> I guess I met the same problem with you. "Git Bash for Windows - Docker install" this means you should download the "git for windows" and Docker, then run git and docker at the same time.

I think it should be the setting problem of the docker environment variable.
I have given up now.
It is a bit less practical for me.

**Comment by ricklamers** [comment]
Docker Toolbox is currently not supported out of the box. Follow #89 for updates, and possibly try @nanayuri's [suggestion](https://github.com/ricklamers/gridstudio/issues/47#issuecomment-519764515) to try a hotfix in the meantime.
