### ISSUE TITLE
Installation on Mac OS Mojave

### ISSUE THREAD

**Issue by Timothy13Munyao** [ricklamers/gridstudio#67]
Is it possible to install on Mac os Mojave?

**Comment by ricklamers** [comment]
@Timothy13Munyao Yes. Make sure you download [Docker for Mac](https://docs.docker.com/docker-for-mac/install/), and [Git for macOS](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and follow the instructions from the [install page](https://github.com/ricklamers/gridstudio/wiki/Installation).
