### ISSUE TITLE
Javascript Error in console

### ISSUE THREAD

**Issue by a4501150** [ricklamers/gridstudio#72]
When we deploy in LAN environment with docker, after login, the following errors are showing in console.

![image](https://user-images.githubusercontent.com/5282745/63130235-bdf5bf00-bf87-11e9-8f8e-807cc8688db4.png)

**Comment by ricklamers** [comment]
@a4501150 Could you provide more details about how you're deploying it? It looks like the HTTP requests are returning an error, but I don't have enough details to see which ones.

**Comment by ricklamers** [comment]
Closing until further details provided (re-open if necessary).
