### ISSUE TITLE
Still cannot reach 127.0.0.1:8080

### ISSUE THREAD

**Issue by WalterLoo** [ricklamers/gridstudio#73]
![2019-08-16_114019](https://user-images.githubusercontent.com/35680889/63142077-ee3a6d80-c01a-11e9-9aa4-03951ddd16ef.png)
![2019-08-16_114127](https://user-images.githubusercontent.com/35680889/63142079-eed30400-c01a-11e9-89ca-db69ffeb4b34.png)

**Comment by ATCGatcg** [comment]
You should use the IP of the docker, not 127.0.0.1.  Run "docker-machine env" to get the IP.

**Comment by simkakashi** [comment]
Or using localhost:8080

**Comment by HuYmoon** [comment]
使用了docker的IP，也打不开，192.168.99.100:8080

**Comment by HuYmoon** [comment]
used the IP of the docker，cannot open

**Comment by JiehaoZhang** [comment]
You may first need to stop your firewall.
1. systemctl stop firewalld.service #stop firewall
2. ./run.sh

**Comment by guistory** [comment]
> used the IP of the docker，cannot open

how to slove it ?

**Comment by JiehaoZhang** [comment]
> > used the IP of the docker，cannot open
> 
> how to slove it ?
If you use Docker Toolbox, the steps as below:
Do you have installed this application "Kitematic (Alpha)"?
If yes, you can open this application, and start "gridstudio" container, which you need to link your docker hub with your github , and create a repo "gridstudio" in github.
Then you can see the login page in the webview.
![无标题](https://user-images.githubusercontent.com/18612682/63648957-fce6fa00-c769-11e9-98ff-24fae05ea2e6.png)

**Comment by JiehaoZhang** [comment]
@guistory 
If you use Docker Toolbox, the steps as below:
Do you have installed this application "Kitematic (Alpha)"?
If yes, you can open this application, and start "gridstudio" container, which you need to link your docker hub with your github , and create a repo "gridstudio" in github.
Then you can see the login page in the webview.
![无标题](https://user-images.githubusercontent.com/18612682/63648991-767ee800-c76a-11e9-8a31-7de07edaca54.png)

**Comment by guistory** [comment]
> @guistory
> If you use Docker Toolbox, the steps as below:
> Do you have installed this application "Kitematic (Alpha)"?
> If yes, you can open this application, and start "gridstudio" container, which you need to link your docker hub with your github , and create a repo "gridstudio" in github.
> Then you can see the login page in the webview.

maybe   you know chinese ,please add my qq 58999395

**Comment by HuYmoon** [comment]
> Kitematic (Alpha)

do you know how to sign in to access grid studio(the page of right)?  thank you 
![image](https://user-images.githubusercontent.com/34277172/63662225-41b57400-c7f0-11e9-91c3-2e42372b0df4.png)

**Comment by ricklamers** [comment]
@WalterLoo it looks like it's not able to download the Docker image from the Docker hub and execute it. Let us know if you've tried turning off your firewall. Feel free to re-open if it keeps failing.
