### ISSUE TITLE
I can't see more than 100 rows ? 

### ISSUE THREAD

**Issue by ForrestSu** [ricklamers/gridstudio#75]
What is the maximum number of rows supported by the gridstudio?

![grid](https://user-images.githubusercontent.com/5516080/63221184-fd125300-c1c7-11e9-8b5d-e0ad2ea63aed.jpg)

**Comment by liupu14** [comment]
The same problem with you, beg for the key to the problem

**Comment by KnightYao** [comment]
same problem

**Comment by jian-kang-computational-physics** [comment]
When executing the following codes, the connection to the server lost immediately. So my guess is: for now the app does not support 100+ rows nor "P"+ columns. When asking values out of the limited range, an internal error occurs.
`sheet("A101", 1.0)`
`sheet("P1", 1.0)`

**Comment by Lpanp** [comment]
same problem

**Comment by ricklamers** [comment]
It's apparently well hidden, but you can right-click the sheet and change its size to get more rows!

![image](https://user-images.githubusercontent.com/1309307/63882916-54d46980-c9d3-11e9-9609-6c72e1a261d7.png)

**Comment by weidongzhou1994** [comment]
It seems that the maximum number of rows is not restricted, but if you set the cells above million,  you will receive this message: You're creating over a million cells, Grid isn't fully optimized yet. This amount could result in degraded user experience, are you sure you want to continue?
