### ISSUE TITLE
can not run the run.sh with ./run.sh

### ISSUE THREAD

**Issue by pythonbaby2019** [ricklamers/gridstudio#76]

**Comment by airrow** [comment]
when I run the run.sh with ./run.sh, the git bash says: 
./run.sh: line 5: docker: command not found
./run.sh: line 11: docker: command not found

And my windows system cannot install docker.
pls help me, thank you very much.

**Comment by sonicwb** [comment]
You need to install docker first. Before you install docker, please make sure you're under Win10 Pro/Ent version. And, remember to use Linux containers and share your install hard drive.

**Comment by ATCGatcg** [comment]
You could try to insatll docker toolbox if you cannot install docker for windows.

**Comment by pythonbaby2019** [comment]
how to install the docker in the deepin linux  ,a chinese OS

**Comment by sonicwb** [comment]
You can check this web site: https://wiki.deepin.org/wiki/Docker
