### ISSUE TITLE
 Error response from daemon: invalid mode: /home/source.

### ISSUE THREAD

**Issue by ATCGatcg** [ricklamers/gridstudio#78]
When i run ./run.sh, it say 
Digest: sha256:c7b2d9aa20ea9903d2ebce119a094114d829f54423c5ab59e0ec23b8ee819905
Status: Downloaded newer image for ricklamers/gridstudio:release
D:\docker_toolbox\docker.exe: Error response from daemon: invalid mode: /home/source.
See 'D:\docker_toolbox\docker.exe run --help'.

What does this mean? I'm sorry i am a newbie on docker.

**Comment by cherrylast** [comment]
path interpretation problem. If you use docker toolbox, don't use run.sh, just input this command:
docker run --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release

**Comment by ATCGatcg** [comment]
Thanks for your help. It works!

**Comment by ricklamers** [comment]
As a note, Docker Toolbox support should be improved. I'll give it some though.

**Comment by Leviathan321** [comment]
I have tried out the command on Windows, but the execution hangs:

docker run --name=gridstudio --rm=false -p 8080:8080 -p 4432:4432 ricklamers/gridstudio:release
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
....

Can someone tell me whats wrong?

Thanks

**Comment by ricklamers** [comment]
@Leviathan321 what do you mean execution hangs? I thing it works as intended. Did you visit `http://localhost:8080`?

**Comment by Leviathan321** [comment]
Yes I tried, it is said that the adress is wrong - so there is nothing hosted?

**Comment by ricklamers** [comment]
> docker run --name=gridstudio --rm=false -p 8080:8080 -p 4432:4432 ricklamers/gridstudio:release

Any reason you changed -p from 4430:4430 to 4432:4432? Might be causing issues.
