### ISSUE TITLE
Issue with path conversion in the run.sh with Docker Desktop for Windows

### ISSUE THREAD

**Issue by Soarnsky** [ricklamers/gridstudio#8]
The run.sh script fails while using Git Bash on Windows

```
 MINGW64 /d/dev/gridstudio (master)
$ ./run.sh
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "D:/dev/gridstudio/grid-app/proxy/userdata;D"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

Related: https://stackoverflow.com/questions/50608301/docker-mounted-volume-adds-c-to-end-of-windows-path-when-translating-from-linux

Changing it to this fixed it:
`docker run --name=gridstudio --rm=false -v /${PWD}/grid-app:/home/source -v /${PWD}/grid-app/proxy/userdata:/home/userdata -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release`

**Comment by AngeloTorelli** [comment]
I can confirm that. I changed the file and the error was gone

**Comment by OtterOriented** [comment]
You can also use:
`MSYS_NO_PATHCONV=1 ./run.sh`

**Comment by ricklamers** [comment]
Should be fixed in a nicer way in the latest run.sh.
