### ISSUE TITLE
It does not work correctly in macos

### ISSUE THREAD

**Issue by databill** [ricklamers/gridstudio#81]
My laptop:
```
Chrome 76
MacOS 10.13.6
```

any program can not run correctly:
```
sheet("B1", 100)
sheet("C1", 1000)
```
only C1 is set, while B1 not.

Even a very simple for loop can not execute including the examples in the repo:
```
for i in range(1,10):
    print (i)
```

The trace log is:
```
Traceback (most recent call last):
  File "python/init.py", line 282, in getAndExecuteInput
  File "<string>", line 1, in <module>
NameError: name 'i' is not defined
```

**Comment by wookim789** [comment]
Hello databill.
I'm just user at grid studio and I had same problem.
First Question about sheet method is well functioned.
So i could'nt help you..
![image](https://user-images.githubusercontent.com/38445103/63404214-47404200-c41d-11e9-9227-3c65ffcd9145.png)
![image](https://user-images.githubusercontent.com/38445103/63404222-4c9d8c80-c41d-11e9-9620-9a1307f28d51.png)

But  And for loop case, I had same issue like you.
Solution is like that.
Select the for loop code and execute at once.
![image](https://user-images.githubusercontent.com/38445103/63404671-15c87600-c41f-11e9-920d-b205d2981ade.png)

It code editor do not work when multi line code,
so you should darg all the multi code line and then execute.

I hope this will help. thank you.

**Comment by databill** [comment]
OK, understood.
I should select the **codes**, and then execute.
