### ISSUE TITLE
there's sth wrong while using pd.read_csv

### ISSUE THREAD

**Issue by simkakashi** [ricklamers/gridstudio#82]
Mac OS and my sample as below:

```
import pandas as pd

pd.read_csv(r'/Users/Simkakashi/Desktop/sample.csv')
```
but it seems sth wrong as "files not found error"

**Comment by 1kastner** [comment]
You are inside a docker image, therefore you can not use the file paths on your normal computer.
Please have a look at the workdir setting in the dockerfile file.

**Comment by ricklamers** [comment]
@1kastner is right. To get some sense of where you are on the file system on the Docker image use the `cd` and `ls` commands in the terminal inside Grid Studio.
