### ISSUE TITLE
 Error response from daemon: invalid mode: /home/source.

### ISSUE THREAD

**Issue by jue12** [ricklamers/gridstudio#83]
![捕获](https://user-images.githubusercontent.com/50287699/63445586-3a4a3f80-c46b-11e9-8582-fc40e1a36e57.PNG)
what is wrong about it ? what can i do,please?

**Comment by wookim789** [comment]
hello jue12.
It's seems like https://github.com/ricklamers/gridstudio/issues/78 this issue.

I hope this help you.

**Comment by jue12** [comment]
> hello jue12.
> It's seems like #78 this issue.
> I hope this help you.
Thanks
