### ISSUE TITLE
can not connect 127.0.0.1:8080

### ISSUE THREAD

**Issue by guistory** [ricklamers/gridstudio#85]
win10 home edition + docker toolbox 
============================================
```
$ docker run --privileged --name=gridstudio --rm=false -p 8080:8080 -p 4430:4430 ricklamers/gridstudio:release
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
```
=================================================
cmd run ''netstat -an'' 8080 port not find

**Comment by ricklamers** [comment]
After you run the `docker run` command, could you run `docker container list` and `docker logs <container id>`?

Just to be clear, when you go to 127.0.0.1:8080 in your browser you get a time-out?

**Comment by guistory** [comment]
thank you for your help

**Comment by 1kastner** [comment]
With your docker toolbox you won't connect to localhost but most likely to `192.168.99.100` or one of the next ip addresses, i.e. `192.168.99.101` etc. Some more information can be found at https://forums.docker.com/t/how-to-use-localhost-instead-of-192-168-99-100/54098
