### ISSUE TITLE
How to install on windows10?

### ISSUE THREAD

**Issue by louxinghao** [ricklamers/gridstudio#87]
I have download Docker and Git Bush, but I still can't use it
Can anybody help me?
It would be better to teach me step by step, thanks!

**Comment by 1kastner** [comment]
Please open either the commandline ("cmd") or a powershell ("ps") and type the command `systeminfo`. Tell me which exact operating system is shown in the second line.

Furthermore, please provide the error message that it fails with.

**Comment by guistory** [comment]
> I have download Docker and Git Bush, but I still can't use it
> Can anybody help me?
> It would be better to teach me step by step, thanks!

if your win10 is home,please download dockertoolbox

**Comment by ricklamers** [comment]
@louxinghao Some general advice, you should try to be as descriptive as possible when asking for help.

Try to explain you can't use it. Are you getting an error? If so, post the error in your message. Are you not seeing something you expect? Tell us what you think should happen. 

This way, we're able to help you much more easily!

Please add details, and re-open.
