### ISSUE TITLE
manipulate several sheets

### ISSUE THREAD

**Issue by cherrylast** [ricklamers/gridstudio#88]
I noticed that data will be only written to "Sheet1"， although it is allowed to add more sheets to the grid. My question is how can I manipulate sheets other than sheet1? Thanks.

**Comment by guistory** [comment]
may be need to fix

**Comment by ricklamers** [comment]
Hi all, sorry for my inactivity on the issues. Been very busy - also in the middle of a move.

If you take a look at how the Python function is defined in [init.py](https://github.com/ricklamers/gridstudio/blob/a2a6c67ff379d66419b68fad4213ff23bbc07af5/grid-app/python/init.py#L167) you can see that you're able to write to different sheets by sheet index.

Top of my head you could do something like:

`sheet("A1:A3", [1, 2, 3], sheet_index=2)`

which would write to the 3rd sheet.
