### ISSUE TITLE
Error message "invalid reference format: repository name must be lowercase." from docker when calling "run.sh"

### ISSUE THREAD

**Issue by ZiniuLu** [ricklamers/gridstudio#91]
![errorMessage](https://user-images.githubusercontent.com/34126026/64077424-d75d7180-ccd0-11e9-9ee5-7d6bd42463d3.png)

**Comment by ZiniuLu** [comment]
I tried to use "$PWD" and "$WIN_PWD" instead of $PWD and $WIN_PWD, than it worked.

**Comment by ricklamers** [comment]
@ZiniuLu Please put the cloned `gridstudio` in a Windows directory without uppercase characters. This is unfortunately a limitiation of running Docker on Windows.
