### ISSUE TITLE
127.0.0.1:8080 refused my connection

### ISSUE THREAD

**Issue by extirpate** [ricklamers/gridstudio#92]
after running ./run.sh   
show this:
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430

and i press"netstate -an |grep 8080",got nothing
i tried to enter  127.0.0.1:8080   localhost:8080  0.0.0.0:8080 in the browser, all failed to connect to the server.  But i enter 127.0.0.1 without the port 8080, i can see "It Works"

**Comment by ricklamers** [comment]
What exactly do you see if you go to 127.0.0.1? Are you sure there is no other program blocking port 8080?

If so, it's probably that Docker is unable to forward port 8080 on your machine to port 8080 on the Docker instance.

**Comment by guistory** [comment]
> after running ./run.sh
> show this:
> --> Updating terminal app.js
> --> Run manager proxy, starting manager.go (compiling with go run ...)
> Listening on port: 8080
> WS Listening on port: 4430
> 
> and i press"netstate -an |grep 8080",got nothing
> i tried to enter 127.0.0.1:8080 localhost:8080 0.0.0.0:8080 in the browser, all failed to connect to the server. But i enter 127.0.0.1 without the port 8080, i can see "It Works"

haha，i met the same iss, may be you run docker use dockertoolbox in win 10 home edition ,please run Kitematic (Alpha) as Administrator.

**Comment by nefigarcia** [comment]
Same problem using dockertoolbox on windows 7, containers are running but i can't display the app.
![listcontainers](https://user-images.githubusercontent.com/21102047/80380555-5c4f5980-8865-11ea-8124-cbc28caf6cd0.PNG)
![run](https://user-images.githubusercontent.com/21102047/80380571-61140d80-8865-11ea-9984-4cc9f42b2af3.JPG)

**Comment by airrow** [comment]
Could you help tell that how can I use docker? Or maybe I just want to know which image can be used as container to login 127.0.0.1:8080.....

**Comment by ricklamers** [comment]
Please walk through https://github.com/ricklamers/gridstudio/wiki/Installation and https://docs.docker.com/get-docker/. If you have any specific issues or errors feel free to post them.

Make sure you read the part about how to user Docker run (both port 4430 and 8080 need to be forwarded as is described in the run.sh).
