### ISSUE TITLE
no Module named 'requests' /  'bs4'

### ISSUE THREAD

**Issue by extirpate** [ricklamers/gridstudio#93]
when i was trying the example codes, i got 
No module named 'requests', 
and i changed the "from bs4 import BeautifulSoup" to the first line, and i got No module named Bs4

in my MacOs, i type
"pip install requests",seems already have it

**Comment by ricklamers** [comment]
These modules aren't installed on the Docker container by default, to install it run `pip3 install beautifulsoup4` on the terminal that is open when you're in the Grid Studio workspace.
