### ISSUE TITLE
Unable to find image 'ricklamers/gridstudio:release' locally

### ISSUE THREAD

**Issue by extirpate** [ricklamers/gridstudio#94]
when i excute "./run.sh"
the termnial shows
Unable to find image 'ricklamers/gridstudio:release' locally
release: Pulling from ricklamers/gridstudio"
"
and downloading a batch of files

every time cost so much time to download? so terrible...

**Comment by ricklamers** [comment]
The first time this happens, it has to download the Docker image from Dockerhub. The second time you invoke ./run.sh it shouldn't happen anymore. Are you removing Docker? Are you sure Docker has the right permissions to write its images to disk persistently?

**Comment by trkwyk** [comment]
> The first time this happens, it has to download the Docker image from Dockerhub. The second time you invoke ./run.sh it shouldn't happen anymore. Are you removing Docker? Are you sure Docker has the right permissions to write its images to disk persistently?

Hello Rick. How do I remove the image? Where is it stored? I want to uninstall it. Your project is wonderful but it is not that handy for me yet. Looking forward to your new releases.

**Comment by ricklamers** [comment]
Here's a quick Google result that should help you out: https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes

Thanks for the feedback, we know that Grid Studio is currently not very accesible/easily installable. Keep an eye out, as this will be significantly improved in the future ; )
